"""Render verbal test cases as a TesterArmy e2e suite (https://e2e.tester.army)."""

import json
import re
from collections.abc import Sequence

from frontier_agent.graphs.document.state import TestCase
from frontier_agent.schemas import Runner, TestKind

_PLACEHOLDER = re.compile(r"\{(\w+)\}")
_CREDENTIAL_FIELDS = ("username", "password")


def safe_name(contract_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", contract_id).strip(".-") or "contract"


def _lit(value: str) -> str:
    """TypeScript string literal (JSON strings are valid TS)."""
    return json.dumps(value, ensure_ascii=False)


def _act(case: TestCase, step: str) -> str:
    names = list(dict.fromkeys(_PLACEHOLDER.findall(step)))
    entries: list[str] = []
    for n in names:
        if n in case.test_data:
            entries.append(f"{_lit(n)}: {_lit(case.test_data[n])}")
        elif case.credentials_role and n in _CREDENTIAL_FIELDS:
            entries.append(f"{_lit(n)}: cred.{n}")
    if not entries:
        return f"  await agent.act({_lit(step)});"
    return f"  await agent.act({_lit(step)}, {{ params: {{ {', '.join(entries)} }} }});"


def _render_test(case: TestCase) -> str:
    lines = [
        f"test({_lit(f'{case.id}: {case.title}')}, async ({{ app, agent }}) => {{",
        f"  await app.open({_lit(case.start_path)});",
    ]
    if case.credentials_role:
        lines.append(f"  const cred = credentials.user({_lit(case.credentials_role)});")
    lines += [_act(case, s) for s in case.steps]
    lines += [f"  await agent.assert({_lit(e)});" for e in case.expected_results]
    lines.append("});")
    return "\n".join(lines)


def render_suite(
    test_cases: Sequence[TestCase],
    contract_id: str,
    contract_version: str,
    out_of_scope: Sequence[str] = (),
) -> dict[str, str]:
    """Return `{path: content}`: `tests/<contract_id>.e2e.ts` (ui cases) and `plan.json`."""
    files: dict[str, str] = {}
    ui = [c for c in test_cases if c.kind == TestKind.UI]
    if ui:
        header = (
            f"// Generated by frontier_agent for contract {_lit(contract_id)} "
            f"version {_lit(contract_version)}. Do not edit by hand.\n"
        )
        imports = "import { test } from '@e2e-dev/web';\n"
        if any(c.credentials_role for c in ui):
            imports += "import { credentials } from 'e2e';\n"
        body = "\n\n".join(_render_test(c) for c in ui)
        files[f"tests/{safe_name(contract_id)}.e2e.ts"] = f"{header}{imports}\n{body}\n"
    plan = {
        "contract_id": contract_id,
        "contract_version": contract_version,
        "test_cases": [
            {
                "id": c.id,
                "clause": c.clause,
                "title": c.title,
                "objective": c.objective,
                "kind": str(c.kind),
                "priority": str(c.priority),
                "runner": str(Runner.TESTERARMY if c.kind == TestKind.UI else Runner.MANUAL_API),
            }
            for c in test_cases
        ],
        "out_of_scope": list(out_of_scope),
    }
    files["plan.json"] = json.dumps(plan, indent=2, ensure_ascii=False) + "\n"
    return files
