"""Render verbal test cases as a TesterArmy e2e suite (https://e2e.tester.army)."""

import json
import re
from collections.abc import Sequence

from frontier_agent.graphs.document.state import TestCase


def _safe_name(contract_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "-", contract_id).strip(".-") or "contract"


def _lit(value: str) -> str:
    """TypeScript string literal (JSON strings are valid TS)."""
    return json.dumps(value, ensure_ascii=False)


def _render_test(case: TestCase) -> str:
    lines = [
        f"test({_lit(f'{case.id}: {case.title}')}, async ({{ app, agent }}) => {{",
        f"  await app.open({_lit(case.start_path)});",
    ]
    lines += [f"  await agent.act({_lit(s)});" for s in case.steps]
    lines += [f"  await agent.assert({_lit(e)});" for e in case.expected_results]
    lines.append("});")
    return "\n".join(lines)


def render_suite(
    test_cases: Sequence[TestCase],
    contract_id: str,
    contract_version: str,
    out_of_scope: Sequence[str] = (),
) -> dict[str, str]:
    """Return `{path: content}`: `tests/<contract_id>.e2e.ts` (ui cases) and `plan.json`."""
    files: dict[str, str] = {}
    ui = [c for c in test_cases if c.kind == "ui"]
    if ui:
        header = (
            f"// Generated by frontier_agent for contract {_lit(contract_id)} "
            f"version {_lit(contract_version)}. Do not edit by hand.\n"
        )
        body = "\n\n".join(_render_test(c) for c in ui)
        files[f"tests/{_safe_name(contract_id)}.e2e.ts"] = (
            f"{header}import {{ test }} from 'e2e';\n\n{body}\n"
        )
    plan = {
        "contract_id": contract_id,
        "contract_version": contract_version,
        "test_cases": [
            {
                "id": c.id,
                "clause": c.clause,
                "title": c.title,
                "objective": c.objective,
                "kind": c.kind,
                "priority": c.priority,
                **({"runner": "manual-api"} if c.kind == "api" else {}),
            }
            for c in test_cases
        ],
        "out_of_scope": list(out_of_scope),
    }
    files["plan.json"] = json.dumps(plan, indent=2, ensure_ascii=False) + "\n"
    return files
