/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Document Invoke */
        post: operations["document_invoke_document_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Document Stream */
        post: operations["document_stream_document_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cicd/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cicd Invoke */
        post: operations["cicd_invoke_cicd_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cicd/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cicd Stream */
        post: operations["cicd_stream_cicd_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Github Webhook
         * @description Stub: validates the signature and parses `workflow_run`. No GitHub/graph call yet.
         */
        post: operations["github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ambiguity */
        Ambiguity: {
            /** Clause */
            clause: string;
            /** Reason */
            reason: string;
            /** Suggested Question */
            suggested_question: string;
        };
        /** CicdInput */
        CicdInput: {
            expected: components["schemas"]["Ref"];
            evidence_ref?: components["schemas"]["Ref"] | null;
            /** Results */
            results?: components["schemas"]["ScenarioResult"][];
        };
        /** CicdState */
        CicdState: {
            expected: components["schemas"]["Ref"];
            evidence_ref?: components["schemas"]["Ref"] | null;
            /** Results */
            results?: components["schemas"]["ScenarioResult"][];
            analysis?: components["schemas"]["Verdict"] | null;
            verdict?: components["schemas"]["Verdict"] | null;
            /**
             * Attestation Authorized
             * @default false
             */
            attestation_authorized: boolean;
            /** Observations */
            observations?: string[];
        };
        /** DocumentInput */
        DocumentInput: {
            /** Contract Id */
            contract_id: string;
            /** Document */
            document: string;
            /** Answers */
            answers?: string[];
        };
        /** DocumentState */
        DocumentState: {
            /** Contract Id */
            contract_id: string;
            /** Document */
            document: string;
            /** Answers */
            answers?: string[];
            /** @default pending */
            status: components["schemas"]["DocumentStatus"];
            /** Clauses */
            clauses?: string[];
            /** Ambiguities */
            ambiguities?: components["schemas"]["Ambiguity"][];
            /** Scenarios */
            scenarios?: components["schemas"]["Scenario"][];
            /** Pending Items */
            pending_items?: string[];
            /**
             * Accepted By Client
             * @default false
             */
            accepted_by_client: boolean;
            /**
             * Accepted By Provider
             * @default false
             */
            accepted_by_provider: boolean;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "needs_clarification" | "proposal";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Ref
         * @description Identifies what is evaluated against: milestone, agreed version and exact revision.
         */
        Ref: {
            /** Milestone Id */
            milestone_id: string;
            /** Contract Version */
            contract_version: string;
            /** Revision */
            revision: string;
        };
        /** Scenario */
        Scenario: {
            /** Clause */
            clause: string;
            /** Description */
            description: string;
            /** Expected Result */
            expected_result: string;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /** Scenario Id */
            scenario_id: string;
            status: components["schemas"]["ScenarioStatus"];
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * ScenarioStatus
         * @enum {string}
         */
        ScenarioStatus: "passed" | "failed" | "skipped" | "error";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "favorable" | "needs_fix" | "inconclusive";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    document_invoke_document_invoke_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_stream_document_stream_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cicd_invoke_cicd_invoke_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CicdInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CicdState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cicd_stream_cicd_stream_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CicdInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string | null;
                "x-github-event"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
