/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Document Invoke */
        post: operations["document_invoke_document_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Document Stream */
        post: operations["document_stream_document_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cicd/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cicd Invoke */
        post: operations["cicd_invoke_cicd_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cicd/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cicd Stream */
        post: operations["cicd_stream_cicd_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Github Webhook
         * @description Stub: validates the signature and parses `workflow_run`. No GitHub/graph call yet.
         */
        post: operations["github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Manifest
         * @description GitHub App manifest for https://github.com/settings/apps/new?manifest_url=...
         */
        get: operations["github_manifest_github_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Github Callback
         * @description Exchange the temporary manifest code for real app credentials.
         */
        get: operations["github_callback_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ambiguity */
        Ambiguity: {
            /** Clause */
            clause: string;
            /** Reason */
            reason: string;
            /** Suggested Question */
            suggested_question: string;
        };
        /** ChangedFile */
        ChangedFile: {
            /** Path */
            path: string;
            /** Content */
            content?: string | null;
        };
        /** CicdInput */
        CicdInput: {
            expected: components["schemas"]["Ref"];
            evidence_ref?: components["schemas"]["Ref"] | null;
            pull_request?: components["schemas"]["PullRequest"] | null;
            /** Expected Test Ids */
            expected_test_ids?: string[];
            /** E2E Report Json */
            e2e_report_json?: string | null;
            /** E2E Junit Xml */
            e2e_junit_xml?: string | null;
            /** Results */
            results?: components["schemas"]["ScenarioResult"][];
            static?: components["schemas"]["StaticReports"];
            /** Clauses */
            clauses?: string[];
        };
        /** CicdState */
        CicdState: {
            expected: components["schemas"]["Ref"];
            evidence_ref?: components["schemas"]["Ref"] | null;
            pull_request?: components["schemas"]["PullRequest"] | null;
            /** Expected Test Ids */
            expected_test_ids?: string[];
            /** E2E Report Json */
            e2e_report_json?: string | null;
            /** E2E Junit Xml */
            e2e_junit_xml?: string | null;
            /** Results */
            results?: components["schemas"]["ScenarioResult"][];
            static?: components["schemas"]["StaticReports"];
            /** Clauses */
            clauses?: string[];
            status?: components["schemas"]["ReviewStatus"] | null;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** E2E Commit */
            e2e_commit?: string | null;
            /** E2E Dirty */
            e2e_dirty?: boolean | null;
            /**
             * E2E Report Parsed
             * @default false
             */
            e2e_report_parsed: boolean;
            /** Static Tools Parsed */
            static_tools_parsed?: components["schemas"]["StaticTool"][];
            analysis?: components["schemas"]["Verdict"] | null;
            agent_dynamic?: components["schemas"]["Verdict"] | null;
            agent_static?: components["schemas"]["Verdict"] | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            dynamic_verdict?: components["schemas"]["Verdict"] | null;
            static_verdict?: components["schemas"]["Verdict"] | null;
            verdict?: components["schemas"]["Verdict"] | null;
            /**
             * Attestation Authorized
             * @default false
             */
            attestation_authorized: boolean;
            /** Observations */
            observations?: string[];
            /**
             * Pr Comment
             * @default
             */
            pr_comment: string;
        };
        /** DocumentInput */
        DocumentInput: {
            /** Contract Id */
            contract_id: string;
            /** Document */
            document: string;
            /** Answers */
            answers?: string[];
            /**
             * Contract Version
             * @default draft
             */
            contract_version: string;
        };
        /** DocumentState */
        DocumentState: {
            /** Contract Id */
            contract_id: string;
            /** Document */
            document: string;
            /** Answers */
            answers?: string[];
            /**
             * Contract Version
             * @default draft
             */
            contract_version: string;
            /** @default pending */
            status: components["schemas"]["DocumentStatus"];
            /** Clauses */
            clauses?: string[];
            /** Ambiguities */
            ambiguities?: components["schemas"]["Ambiguity"][];
            /** Test Cases */
            test_cases?: components["schemas"]["TestCase"][];
            /** Out Of Scope */
            out_of_scope?: string[];
            /** E2E Suite */
            e2e_suite?: {
                [key: string]: string;
            };
            /** Pending Items */
            pending_items?: string[];
            /**
             * Accepted By Client
             * @default false
             */
            accepted_by_client: boolean;
            /**
             * Accepted By Provider
             * @default false
             */
            accepted_by_provider: boolean;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "pending" | "needs_clarification" | "proposal" | "llm_unavailable";
        /** E2EStep */
        E2EStep: {
            /**
             * Title
             * @default
             */
            title: string;
            verdict: components["schemas"]["E2EStepVerdict"];
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * E2EStepVerdict
         * @description Per-step verdict of a TesterArmy agent step (`report.json`).
         * @enum {string}
         */
        E2EStepVerdict: "passed" | "failed" | "blocked" | "exhausted" | "skipped";
        /** Finding */
        Finding: {
            source: components["schemas"]["FindingSource"];
            severity: components["schemas"]["Severity"];
            /** Message */
            message: string;
            /** Path */
            path?: string | null;
            /** Line */
            line?: number | null;
            /** Rule */
            rule?: string | null;
            /** Test Id */
            test_id?: string | null;
            /**
             * Blocking
             * @default false
             */
            blocking: boolean;
        };
        /**
         * FindingSource
         * @enum {string}
         */
        FindingSource: "e2e" | "ruff" | "eslint" | "mypy" | "tsc" | "format" | "indentation" | "review";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "medium" | "low";
        /** PullRequest */
        PullRequest: {
            /** Number */
            number: number;
            /** Head Sha */
            head_sha: string;
            /**
             * Base Sha
             * @default
             */
            base_sha: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Diff
             * @default
             */
            diff: string;
            /** Changed Files */
            changed_files?: components["schemas"]["ChangedFile"][];
        };
        /**
         * Ref
         * @description Identifies what is evaluated against: milestone, agreed version and exact revision.
         */
        Ref: {
            /** Milestone Id */
            milestone_id: string;
            /** Contract Version */
            contract_version: string;
            /** Revision */
            revision: string;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "reviewed" | "llm_required" | "no_verdict";
        /** ScenarioResult */
        ScenarioResult: {
            /** Scenario Id */
            scenario_id: string;
            status: components["schemas"]["ScenarioStatus"];
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Steps */
            steps?: components["schemas"]["E2EStep"][];
        };
        /**
         * ScenarioStatus
         * @enum {string}
         */
        ScenarioStatus: "passed" | "failed" | "skipped" | "error";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "error" | "warning" | "info";
        /**
         * StaticReports
         * @description Raw tool outputs; None = the tool was not run.
         */
        StaticReports: {
            /** Ruff Json */
            ruff_json?: string | null;
            /** Eslint Json */
            eslint_json?: string | null;
            /** Mypy Output */
            mypy_output?: string | null;
            /** Tsc Output */
            tsc_output?: string | null;
            /** Unformatted Files */
            unformatted_files?: string[];
        };
        /**
         * StaticTool
         * @enum {string}
         */
        StaticTool: "ruff" | "eslint" | "mypy" | "tsc" | "format";
        /**
         * TestCase
         * @description Verbal test case: plain-language steps and expectations for an agentic E2E runner.
         */
        TestCase: {
            /** Id */
            id: string;
            /** Clause */
            clause: string;
            /** Title */
            title: string;
            /** Objective */
            objective: string;
            /** Preconditions */
            preconditions?: string[];
            /** Steps */
            steps?: string[];
            /** Expected Results */
            expected_results?: string[];
            /**
             * Start Path
             * @default /
             */
            start_path: string;
            /** @default ui */
            kind: components["schemas"]["TestKind"];
            /** @default medium */
            priority: components["schemas"]["Priority"];
            /** Test Data */
            test_data?: {
                [key: string]: string;
            };
            /** Credentials Role */
            credentials_role?: string | null;
        };
        /**
         * TestKind
         * @enum {string}
         */
        TestKind: "ui" | "api";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "favorable" | "needs_fix" | "inconclusive";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    document_invoke_document_invoke_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_stream_document_stream_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cicd_invoke_cicd_invoke_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CicdInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CicdState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cicd_stream_cicd_stream_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CicdInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string | null;
                "x-github-event"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_manifest_github_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    github_callback_github_callback_get: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
