/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documental/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Documental Invoke */
        post: operations["documental_invoke_documental_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documental/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Documental Stream */
        post: operations["documental_stream_documental_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cicd/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cicd Invoke */
        post: operations["cicd_invoke_cicd_invoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cicd/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cicd Stream */
        post: operations["cicd_stream_cicd_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Github Webhook
         * @description Stub: valida firma y parsea `workflow_run`. No llama a GitHub ni al grafo todavía.
         */
        post: operations["github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ambiguedad */
        Ambiguedad: {
            /** Inciso */
            inciso: string;
            /** Motivo */
            motivo: string;
            /** Pregunta Sugerida */
            pregunta_sugerida: string;
        };
        /** CicdInput */
        CicdInput: {
            esperado: components["schemas"]["Ref"];
            evidencia_ref?: components["schemas"]["Ref"] | null;
            /** Resultados */
            resultados?: components["schemas"]["ScenarioResult"][];
        };
        /** CicdState */
        CicdState: {
            esperado: components["schemas"]["Ref"];
            evidencia_ref?: components["schemas"]["Ref"] | null;
            /** Resultados */
            resultados?: components["schemas"]["ScenarioResult"][];
            analisis?: components["schemas"]["Verdict"] | null;
            veredicto?: components["schemas"]["Verdict"] | null;
            /**
             * Atestacion Autorizada
             * @default false
             */
            atestacion_autorizada: boolean;
            /** Observaciones */
            observaciones?: string[];
        };
        /** DocumentalInput */
        DocumentalInput: {
            /** Contrato Id */
            contrato_id: string;
            /** Documento */
            documento: string;
            /** Respuestas */
            respuestas?: string[];
        };
        /** DocumentalState */
        DocumentalState: {
            /** Contrato Id */
            contrato_id: string;
            /** Documento */
            documento: string;
            /** Respuestas */
            respuestas?: string[];
            /** @default pendiente */
            estado: components["schemas"]["EstadoDocumental"];
            /** Incisos */
            incisos?: string[];
            /** Ambiguedades */
            ambiguedades?: components["schemas"]["Ambiguedad"][];
            /** Escenarios */
            escenarios?: components["schemas"]["Escenario"][];
            /** Pendientes */
            pendientes?: string[];
            /**
             * Aceptado Por Cliente
             * @default false
             */
            aceptado_por_cliente: boolean;
            /**
             * Aceptado Por Proveedor
             * @default false
             */
            aceptado_por_proveedor: boolean;
        };
        /** Escenario */
        Escenario: {
            /** Inciso */
            inciso: string;
            /** Descripcion */
            descripcion: string;
            /** Resultado Esperado */
            resultado_esperado: string;
        };
        /**
         * EstadoDocumental
         * @enum {string}
         */
        EstadoDocumental: "pendiente" | "necesita_aclaracion" | "propuesta";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Ref
         * @description Identifica contra qué se evalúa: hito, versión acordada y revisión exacta.
         */
        Ref: {
            /** Hito Id */
            hito_id: string;
            /** Contrato Version */
            contrato_version: string;
            /** Revision */
            revision: string;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /** Scenario Id */
            scenario_id: string;
            status: components["schemas"]["ScenarioStatus"];
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * ScenarioStatus
         * @enum {string}
         */
        ScenarioStatus: "passed" | "failed" | "skipped" | "error";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "favorable" | "requiere_correccion" | "inconcluso";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    documental_invoke_documental_invoke_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentalState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    documental_stream_documental_stream_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cicd_invoke_cicd_invoke_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CicdInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CicdState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cicd_stream_cicd_stream_post: {
        parameters: {
            query?: {
                thread_id?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CicdInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-hub-signature-256"?: string | null;
                "x-github-event"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
